[package]
name = "sqlite-serve"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
ngx = "0.5.0"
rusqlite = "0.37.0"
handlebars = "6.3.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.145"
