name: "Build Nix package"

on:
  push:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, 
        #macos-latest
        ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v14
        with:
          name: sqlite-serve
          authToken: '${{ secrets.CACHIX_TOKEN }}'

      - name: Build package
        run: nix build -L

      - name: Check build output
        run: |
          ls -lah result/
          ls -lah result/lib/

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sqlite-serve-${{ matrix.os }}
          path: |
            result/lib/*
            result/bin/*
          retention-days: 30
